services:
  db:
    image: postgres:15
    container_name: postgres_patents
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: patents_db
    ports:
      - "5434:5432"  # Porta 5434 no host mapeada para 5432 no container
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: etl_patents
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432  # Porta interna do container PostgreSQL
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: patents_db
    volumes:
      - .:/app
    command: ["python", "src/app.py"]

volumes:
  postgres_data: